=== kubco2/cvWebGen/xml/cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="cv">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta" type="metaType"/>
                <xs:element name="personal" type="personalType"/>
                <xs:element name="address" type="addressType"/>
                <xs:element name="contacts">
                    <xs:complexType>
                        <xs:choice minOccurs="1" maxOccurs="unbounded">
                            <xs:element name="phone">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="type" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" type="emailType"/>
                            <xs:element name="website" type="xs:anyURI"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="works">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="work" type="workType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="educations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="education" type="educationType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skill" type="skillType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="languages">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="language" type="languageType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Types definition -->
    <xs:complexType name="metaType">
        <xs:sequence>
            <xs:element name="created" type="xs:dateTime"/>
            <xs:element name="modified" type="xs:dateTime"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="privacy">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="private"/>
                        <xs:enumeration value="public"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personalType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="middleName" type="xs:string" minOccurs="0"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="dateofbirth" type="xs:date"/>
            <xs:element name="gender">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="male"/>
                        <xs:enumeration value="female"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="nationality"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="zip" type="xs:string"/>
            <xs:element name="state" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="workType">
        <xs:sequence>
            <xs:element type="periodType" name="period"/>
            <xs:element type="xs:string" name="employer"/>
            <xs:element type="xs:string" name="position"/>
            <xs:element type="xs:string" name="activities" minOccurs="0"/>
            <xs:element type="xs:string" name="sector" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="educationType">
        <xs:sequence>
            <xs:element type="periodType" name="period"/>
            <xs:element type="xs:string" name="organisation"/>
            <xs:element type="xs:string" name="description"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="skillType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="languageType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="level" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="novice"/>
                            <xs:enumeration value="beginner"/>
                            <xs:enumeration value="intermediate"/>
                            <xs:enumeration value="advanced"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="periodType">
        <xs:sequence>
            <xs:element name="from" type="dateType"/>
            <xs:element name="to" type="dateType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dateType">
        <xs:sequence>
            <xs:element name="year" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1900"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="month" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="day" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="31"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.(([0-9]{1,3})|([a-zA-Z]{2,3}))"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== kubco2/cvWebGen/xml/carlos.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv.xsd">
    <meta>
        <created>2012-05-24T16:01:51</created>
        <modified>2012-05-24T16:01:51</modified>
        <email>carlos@example.com</email>
        <privacy>public</privacy>
    </meta>
    <personal>
        <firstName>Carlos</firstName>
        <middleName>Los</middleName>
        <lastName>Amores</lastName>
        <dateofbirth>1967-01-01</dateofbirth>
        <gender>male</gender>
        <nationality>Spanish</nationality>
    </personal>
    <address>
        <street>Krnenska 44</street>
        <city>Praha</city>
        <zip>123 41</zip>
        <state>Czech Republic</state>
    </address>
    <contacts>
        <phone type="home">+420 777 231 252</phone>
        <phone type="work">+420 603 523 623</phone>
        <email>carlos@postas.es</email>
    </contacts>
    <works>
        <work>
            <period>
                <from><year>1990</year></from>
                <to><year>2011</year></to>
            </period>
            <employer>ČSA a.s.</employer>
            <position>IT konzultant</position>
            <activities>systémový inženýr, správa a podpora aplikací UNIXInformix a Windows.</activities>
        </work>
    </works>
    <educations>
       <education>
           <period>
               <from><year>1979</year></from>
               <to><year>1979</year></to>
           </period>
           <organisation>SPŠ Most - elektrotechnika</organisation>
           <description>Středoškolské nebo vyučení s maturitou</description>
       </education>
        <education>
            <period>
                <from><year>1998</year></from>
                <to><year>2001</year></to>
            </period>
            <organisation>SOŠ a SOU spojů a elektrotechniky</organisation>
            <description>Středoškolské nebo vyučení s maturitou</description>
        </education>
    </educations>
    <skills>
        <skill name="Operační systémy">MS Windows XP</skill>
        <skill name="Běžné programy">MS Word</skill>
        <skill name="Databázové systémy">SQL</skill>
    </skills>
    <languages>
        <language level="advanced">Angličtina</language>
    </languages>
</cv>

=== kubco2/cvWebGen/xml/bara.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv.xsd">
    <meta>
        <created>2012-08-24T16:12:33</created>
        <modified>2012-08-24T16:12:33</modified>
        <email>bara@example.com</email>
        <privacy>private</privacy>
    </meta>
    <personal>
        <firstName>Bara</firstName>
        <middleName></middleName>
        <lastName>Rikovska</lastName>
        <dateofbirth>1967-04-01</dateofbirth>
        <gender>female</gender>
        <nationality>Czech</nationality>
    </personal>
    <address>
        <street>Kolínska 44</street>
        <city>Nymburk</city>
        <zip>676 15</zip>
        <state>Czech Republic</state>
    </address>
    <contacts>
        <phone type="home">+420 777 451 312</phone>
        <phone type="work">+420 603 312 425</phone>
        <email>bara@email.cz</email>
    </contacts>
    <works>
        <work>
            <period>
                <from>
                    <year>2009</year>
                    <month>10</month>
                </from>
                <to>
                    <year>2010</year>
                    <month>11</month>
                </to>
            </period>
            <employer>Dětský domov se školou Býchory</employer>
            <position>Vychovatel</position>
            <activities>Školství, výuka, vzdělání</activities>
        </work>
        <work>
            <period>
                <from>
                    <year>2000</year>
                </from>
                <to>
                    <year>2006</year>
                </to>
            </period>
            <employer>Plaček s.r.o.</employer>
            <position>Hlavní účetní</position>
            <activities>Hlavní účetní </activities>
            <sector>Ekonomika a finance</sector>
        </work>
        <work>
            <period>
                <from>
                    <year>2011</year>
                    <month>3</month>
                </from>
                <to>
                    <year>2012</year>
                    <month>9</month>
                </to>
            </period>
            <employer>Oblastní nemocnice Kolín a. s.</employer>
            <position>Ergoterapeut</position>
            <activities>Práce s pacienty na oddělení neurologie, geriatrie,interny,ARO.(Basální stimulace, cvičení,kognitivní rhb.)</activities>
            <sector>Zdravotnictví</sector>
        </work>
    </works>
    <educations>
       <education>
           <period>
               <from><year>2003</year></from>
               <to><year>2005</year></to>
           </period>
           <organisation>Vyšší odborná škola v Mostě</organisation>
           <description>Diplomovaný ergoterapeut</description>
       </education>
        <education>
            <period>
                <from><year>2006</year></from>
                <to><year>2008</year></to>
            </period>
            <organisation>Univerzita Hradec Králové</organisation>
            <description>Sociálně výchovná péče o smyslově postižené</description>
        </education>
        <education>
            <period>
                <from><year>2008</year></from>
                <to><year>2010</year></to>
            </period>
            <organisation>Univerzita Hradec Králové</organisation>
            <description>Management rehabilitační činnosti ve speciálních zařízeních a speciální pedagogika</description>
        </education>
    </educations>
    <skills>
        <skill name="Operační systémy">MS Windows XP</skill>
        <skill name="Běžné programy">MS Word</skill>
    </skills>
    <languages>
        <language level="advanced">Angličtina</language>
    </languages>
</cv>

=== kubco2/cvWebGen/xml/anna.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv.xsd">
    <meta>
        <created>2012-05-24T16:12:33</created>
        <modified>2012-05-24T16:12:33</modified>
        <email>jana@example.com</email>
        <privacy>public</privacy>
    </meta>
    <personal>
        <firstName>Anna</firstName>
        <lastName>Cermakova</lastName>
        <dateofbirth>1985-03-15</dateofbirth>
        <gender>female</gender>
        <nationality>Czech</nationality>
    </personal>
    <address>
        <street>Soukenicka 15</street>
        <city>Kolín</city>
        <zip>545 12</zip>
        <state>Czech Republic</state>
    </address>
    <contacts>
        <phone type="home">+420 777 456 789</phone>
        <phone type="work">+420 603 222 333</phone>
        <email>anicka@email.cz</email>
    </contacts>
    <works>
        <work>
            <period>
                <from>
                    <year>1994</year>
                </from>
                <to>
                    <year>2000</year>
                </to>
            </period>
            <employer>Kobla s.r.o.</employer>
            <position>Hlavní účetní</position>
            <activities>mzdová účetní, majetková účetní ,celní deklarant,hlavní účetní</activities>
            <sector>Ekonomika a finance</sector>
        </work>
        <work>
            <period>
                <from>
                    <year>2000</year>
                </from>
                <to>
                    <year>2006</year>
                </to>
            </period>
            <employer>Plaček s.r.o.</employer>
            <position>Hlavní účetní</position>
            <activities>Hlavní účetní </activities>
            <sector>Ekonomika a finance</sector>
        </work>
        <work>
            <period>
                <from>
                    <year>2004</year>
                </from>
                <to>
                    <year>2006</year>
                </to>
            </period>
            <employer>Beaphar Earstern Europe s.r.o.</employer>
            <position>Ekonom</position>
            <activities>ekonom obce , zpracování mezd , celkového účetnictví rozpočtové organizace , staristiky , rozpočty, DPPO , DPFO závislá činnost</activities>
            <sector>Ekonomika a finance</sector>
        </work>
        <work>
            <period>
                <from>
                    <year>2006</year>
                </from>
                <to>
                    <year>2012</year>
                </to>
            </period>
            <employer>BT Audit s.r.o.</employer>
            <position>Odborný asistent v ekonomii</position>
            <activities>odborný asistent , ( spojeno s vedením účetnictví 9 firem , mzdy 9 firem , celkový servis klientům od prvočátečního zaúčtování až k předání daňového přiznání, silniční daně . daně z nemovitosti, DPPO, DPFO ze závislé činn, DPFO</activities>
            <sector>Ekonomika a finance</sector>
        </work>
    </works>
    <educations>
       <education>
           <period>
               <from><year>1981</year></from>
               <to><year>1985</year></to>
           </period>
           <organisation>Gymnázium Nymburk</organisation>
           <description>Středoškolské nebo vyučení s maturitou</description>
       </education>
    </educations>
    <skills>
        <skill name="Operační systémy">MS Windows XP / Vista, MS Windows 98 / ME</skill>
        <skill name="Běžné programy">Textový editor (MS Word), Tabulkový kalkulátor (MS Excel), Internet / e-mail</skill>
    </skills>
    <languages>
        <language level="advanced">Němčina</language>
        <language level="beginner">Ruština</language>
    </languages>
</cv>
